name: Build and Test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Move to sources directory
      run: cd sources    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Execute test
      run: dotnet test
